# name: Pyright
# on:
#     push:
#         branches: [main, develop]
#     pull_request:
#         branches: [main]

# jobs:
#     pyright:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v4

#             - name: Set up Python 3.8.10
#               uses: actions/setup-python@v5
#               with:
#                   python-version: "3.8.10"

#             - name: Setup uv
#               uses: astral-sh/setup-uv@v3
#               with:
#                   enable-cache: true

#             - name: Install dependencies with uv
#               run: |
#                   uv pip install pyright
#                   # 如果有项目依赖
#                   uv pip install -r requirements.txt  # 或 uv sync（若用 pyproject.toml + uv project）

#             - name: Run Pyright
#               run: pyright
